branches:
  only:
    - master

configuration: Release

install:
  - ps: .\.nuget\nuget.exe restore .\Unity.log4netInjection.sln

assembly_info:
  patch: true

build:
  publish_nuget: true

deploy:
  provider: NuGet
  api_key:
    secure: TFTKac0CbCOvowsFmuUzFjjIcRNJNJnigSh568rlQcjSn2E3JjWbVcobqVD3wGtl
  skip_symbols: true
  artifact: /.*\.nupkg/